title: "Game Slot Aset Tetap"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: "/DIPAYANG-Game-2.1" # Ganti dengan nama repositori Anda (pastikan sesuai dengan URL GitHub Pages)
